version: "3"
services:
  gateway:
    build: ./gateway
    command: yarn start:dev
    env_file:
      - .env
      - ./gateway/gateway.env
    depends_on:
      - rabbitmq
      - user
      - token
      - mailer
      - permission
      - group
    ports:
      - "7000:7000"
    volumes:
      - ./gateway:/usr/app
      - /usr/app/node_modules
    networks:
      - backend

  meta:
    build: ./meta
    command: yarn start:dev
    depends_on:
      - rabbitmq
      - meta-db
    links:
      - rabbitmq
    env_file:
      - .env
      - ./meta/meta.env
    ports:
      - "[service-port]:[service-port]"
    volumes:
      - ./meta:/usr/app
      - /usr/app/node_modules
    networks:
      - backend
  # POSTGRES DB
  meta-db:
    container_name: meta-postgres
    volumes:
      - /data/meta-postgres:/data/postgres
    env_file:
      - ./meta/meta.env
    image: postgres:alpine
    ports:
      - "[db-port]:5432"
    networks:
      - backend
      - meta-postgres

  # TOKEN SERVICE CONFIGURATION
  token:
    build: ./token
    command: yarn start:dev
    depends_on:
      - rabbitmq
      - token-db
    links:
      - rabbitmq
    env_file:
      - .env
      - ./token/token.env
    ports:
      - "7101:7101"
    volumes:
      - ./token:/usr/app
      - /usr/app/node_modules
    networks:
      - backend
  # POSTGRES DB
  token-db:
    container_name: token-postgres
    volumes:
      - /data/token-postgres:/data/postgres
    env_file:
      - ./token/token.env
    image: postgres:alpine
    ports:
      - "7201:5432"
    networks:
      - token-postgres
      - backend

  # MAILER SERVICE CONFIGURATION
  mailer:
    build: ./mailer
    command: yarn start:dev
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    env_file:
      - .env
      - ./mailer/mailer.env
    ports:
      - "8020:8020"
    volumes:
      - ./mailer:/usr/app
      - /usr/app/node_modules
    networks:
      - backend

  #RABBITMQ CONFIGURATION
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - backend

  # NETWORKS
networks:
  backend:
  user-postgres:
    driver: bridge
  token-postgres:
    driver: bridge
